# Generated by Django 4.2.2 on 2023-06-14 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_article_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jouralist',
            new_name='Journalist',
        ),
    ]
