# Generated by Django 4.2.2 on 2023-06-15 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_email', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=200)),
                ('job_description', models.TextField()),
                ('salary', models.FloatField()),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField()),
                ('available', models.BooleanField()),
            ],
        ),
    ]
