# Generated by Django 4.2.2 on 2023-06-15 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobBoard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
